// Offline functional/UI tests in a disposable profile.
const {chromium} = require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const assert = require('node:assert/strict');
const path = require('node:path');
const fs = require('node:fs');
const root = path.resolve(__dirname,'..');
const artifacts = path.resolve(process.env.AUDIT_ARTIFACTS || path.join(root,'..','audit-artifacts'));
fs.mkdirSync(artifacts,{recursive:true});
let passed=0;
function ok(label){passed++; console.log('PASS: '+label);}
async function storage(page,settings={}) {
  await page.evaluate(settings=>{
    window.auditStored={ebayLaptopHelperSettings:settings}; window.auditWrites=0; window.auditReads=0; window.auditScans=0;
    window.chrome={runtime:{},storage:{local:{get(keys,callback){auditReads++; callback(structuredClone(auditStored));},set(values,callback){auditWrites++; Object.assign(auditStored,structuredClone(values)); callback?.();}},onChanged:{addListener(fn){window.auditChanged=fn;}}}};
    window.auditSettings = values=>{Object.assign(auditStored.ebayLaptopHelperSettings,values); auditChanged({ebayLaptopHelperSettings:{newValue:structuredClone(auditStored.ebayLaptopHelperSettings)}},'local');};
  },settings);
}
async function install(page) {
  await page.addStyleTag({path:path.join(root,'content.css')});
  for (const name of ['core.js','inspection.js','translation.js']) await page.addScriptTag({path:path.join(root,name)});
  await page.addScriptTag({content:fs.readFileSync(path.join(root,'content.js'),'utf8').replace('function scan() {','function scan() { globalThis.auditScans++;')});
}
async function wait(page){await page.waitForTimeout(400);}
(async()=>{
  const browser=await chromium.launch({headless:true,...(process.env.CHROME_EXECUTABLE?{executablePath:process.env.CHROME_EXECUTABLE}:{})});
  const errors=[];
  try {
    const context=await browser.newContext({viewport:{width:1100,height:900}});
    const page=await context.newPage(); page.on('pageerror',e=>errors.push(e.message));
    await context.route('**/*',route=>route.fulfill({contentType:'text/html',body:'<main id="mainContent"></main><header id="unrelated"></header>'}));
    await page.goto('https://www.ebay.com/sch/i.html');
    await page.setContent(fs.readFileSync(path.join(root,'tests/fixture.html'),'utf8').replace(/<script[\s\S]*?<\/script>/g,''));
    await storage(page,{markNewItems:true,showRiskBadges:true});
    await install(page);
    await page.waitForSelector('[data-ebay-helper-converted]');
    assert.equal(await page.locator('.ebay-helper-card').count(),3);
    assert.equal(await page.locator('[data-ebay-helper-sold]').count(),3);
    assert.equal(await page.locator('[data-ebay-helper-olx]').count(),3);
    assert.match(await page.locator('[data-ebay-helper-converted]').first().textContent(),/14\s*786/);
    assert.equal(await page.locator('[data-ebay-helper-risk], [data-ebay-helper-new]').count(),0);
    assert.equal(await page.evaluate(()=>auditWrites),0);
    ok('catalog totals, links, old settings and removed features');
    await page.screenshot({path:path.join(artifacts,'catalog.png'),fullPage:true});
    await page.locator('.s-card__price').evaluate(el=>el.textContent='US $100.00'); await wait(page);
    assert.match(await page.locator('[data-ebay-helper-converted]').first().textContent(),/7\s*196/);
    await page.locator('[data-ebay-helper-sold]').first().evaluate(el=>el.remove()); await wait(page);
    assert.equal(await page.locator('[data-ebay-helper-sold]').count(),3);
    ok('dynamic price updates and restoration of removed links');
    await page.locator('meta[itemprop="priceCurrency"]').evaluate(el=>el.setAttribute('content','CAD'));
    await wait(page);
    assert.equal(await page.locator('li').nth(2).locator('[data-ebay-helper-converted]').count(),0);
    ok('CAD metadata is never shown as a USD total');
    await page.evaluate(()=>auditSettings({showConvertedPrice:false,showSoldSearch:false})); await wait(page);
    assert.equal(await page.locator('[data-ebay-helper-converted], [data-ebay-helper-sold]').count(),0);
    await page.evaluate(()=>auditSettings({enabled:false})); await wait(page);
    assert.equal(await page.locator('[data-ebay-helper-owned], .ebay-helper-card').count(),0);
    const scans=await page.evaluate(()=>auditScans);
    await page.locator('.s-card__price').evaluate(el=>el.textContent='US $300.00'); await wait(page);
    assert.equal(await page.evaluate(()=>auditScans),scans);
    await page.evaluate(()=>auditSettings({enabled:true,showConvertedPrice:true,showSoldSearch:true})); await wait(page);
    assert.match(await page.locator('[data-ebay-helper-converted]').first().textContent(),/17\s*316/);
    ok('feature switches and no scans while disabled');
    await page.evaluate(()=>auditSettings({preferredKeywords:'ThinkPad',excludedKeywords:'EliteBook',greenTitleColor:'#123456'})); await wait(page);
    assert.ok(await page.locator('li').first().evaluate(el=>el.classList.contains('ebay-helper-preferred')));
    assert.ok(await page.locator('li').nth(1).evaluate(el=>el.classList.contains('ebay-helper-excluded')));
    assert.equal(await page.locator('li').first().evaluate(el=>el.style.getPropertyValue('--ebay-helper-title-color')),'#c17d00');
    await page.evaluate(()=>auditSettings({greenMaxUah:20000,yellowMaxUah:30000})); await wait(page);
    assert.equal(await page.locator('li').first().evaluate(el=>el.style.getPropertyValue('--ebay-helper-title-color')),'#123456');
    ok('preferred and excluded words, thresholds and custom title colors');
    await page.evaluate(()=>{
      document.querySelector('ul').insertAdjacentHTML('beforeend','<li class="brwrvr__item-card"><div class="brwrvr__item-card__body"><a class="bsig__title__wrapper" href="https://www.ebay.com/p/9048104800"><h3 class="bsig__title__text">Microsoft Surface Pro 7 8GB 256GB SSD</h3></a><span class="bsig__price bsig__price--displayprice">$335.00</span><span class="bsig__logisticsCost">Free international shipping</span></div></li>');
    }); await wait(page);
    const latestCard=page.locator('li').last();
    assert.match(await latestCard.locator('[data-ebay-helper-converted]').textContent(),/18\s*331/);
    assert.match(await latestCard.locator('[data-ebay-helper-converted]').getAttribute('title'),/безкоштовна/);
    ok('current category signals, international free shipping and product links');
    const beforeHidden=await page.evaluate(()=>auditScans);
    await page.evaluate(()=>{Object.defineProperty(document,'hidden',{configurable:true,value:true}); document.dispatchEvent(new Event('visibilitychange')); document.querySelector('.s-card__price').textContent='US $250.00';});
    await wait(page); assert.equal(await page.evaluate(()=>auditScans),beforeHidden);
    await page.evaluate(()=>{Object.defineProperty(document,'hidden',{configurable:true,value:false}); document.dispatchEvent(new Event('visibilitychange'));});
    await wait(page); assert.match(await page.locator('[data-ebay-helper-converted]').first().textContent(),/14\s*786/);
    ok('hidden tabs suspend work and catch up when shown');

    await page.goto('https://www.ebay.com/itm/123456789012');
    await page.setContent(fs.readFileSync(path.join(root,'tests/item-fixture.html'),'utf8').replace(/<script[\s\S]*?<\/script>/g,''));
    await storage(page); await install(page); await page.waitForSelector('#ebay-laptop-helper-item-panel');
    const panel=page.locator('#ebay-laptop-helper-item-panel');
    assert.match(await panel.locator('.ebay-helper-item-total').textContent(),/14\s*786/);
    assert.equal(await panel.locator('details[open]').count(),0);
    assert.equal(await panel.locator('.ebay-helper-item-risk').count(),0);
    const actionsTop=await panel.locator('.ebay-helper-item-actions').evaluate(el=>el.getBoundingClientRect().top);
    const factsTop=await panel.locator('[data-section="facts"]').evaluate(el=>el.getBoundingClientRect().top);
    assert.ok(actionsTop<factsTop);
    await page.screenshot({path:path.join(artifacts,'item-desktop.png'),fullPage:true});
    ok('compact item panel keeps price and comparison actions first');
    await panel.locator('[data-section="search"] summary').click();
    await panel.getByRole('textbox',{name:'Запит для пошуку аналогів'}).fill('Dell Latitude custom search');
    await page.locator('.ux-labels-values--shipping').evaluate(el=>el.textContent='Shipping: US $25.00'); await wait(page);
    assert.equal(await panel.getByRole('textbox',{name:'Запит для пошуку аналогів'}).inputValue(),'Dell Latitude custom search');
    assert.ok(await panel.getByRole('textbox',{name:'Запит для пошуку аналогів'}).evaluate(el=>el===document.activeElement));
    assert.match(await panel.locator('[data-section="search"]').getByRole('link',{name:'SOLD',exact:true}).getAttribute('href'),/Dell%20Latitude%20custom%20search/);
    ok('edited search, focus and links survive panel updates');
    await panel.locator('[data-section="checks"] summary').click();
    await panel.getByRole('button',{name:'Підготувати питання англійською'}).click();
    assert.match(await panel.getByRole('textbox',{name:'Питання продавцю — можна редагувати й скопіювати'}).inputValue(),/Hello!/);
    await page.evaluate(()=>Object.defineProperty(window,'Translator',{configurable:true,writable:true,value:undefined}));
    await panel.getByRole('button',{name:'Перекласти українською',exact:true}).click(); await wait(page);
    assert.match(await panel.locator('.ebay-helper-translation-error').last().textContent(),/недоступний/);
    await page.evaluate(()=>{window.Translator={availability:async()=> 'available',create:async()=>({translate:async text=>'UK: '+text})};});
    await panel.getByRole('button',{name:'Перекласти українською',exact:true}).click();
    await page.waitForSelector('button[aria-pressed="true"]');
    assert.match(await panel.locator('[data-section="facts"]').textContent(),/UK:/);
    await panel.getByRole('button',{name:'Показати оригінал',exact:true}).click(); await wait(page);
    assert.doesNotMatch(await panel.locator('[data-section="facts"]').textContent(),/UK:/);
    ok('seller questions, unavailable translator, translation and original toggle');
    await page.setViewportSize({width:360,height:800});
    await page.addStyleTag({content:'body{padding:12px!important} #mainContent{padding:12px!important}'});
    assert.ok(await panel.evaluate(el=>el.getBoundingClientRect().right<=innerWidth));
    await page.screenshot({path:path.join(artifacts,'item-narrow.png'),fullPage:true});
    ok('item panel fits a narrow window');
    await page.evaluate(()=>{
      const section=document.createElement('div'); section.id='viTabs_0_is';
      section.innerHTML='<dl><div class="ux-layout-section-evo__col"><dt>RAM Size</dt><dd>16 GB</dd></div><div class="ux-layout-section-evo__col"><dt>SSD Capacity</dt><dd>1 TB</dd></div></dl>';
      document.querySelector('#mainContent').append(section);
    }); await wait(page);
    assert.match(await panel.locator('.ebay-helper-translation-error').first().textContent(),/Характеристики eBay: 16 GB/);
    assert.match(await panel.textContent(),/Характеристики eBay: 1024 GB/);
    ok('current eBay item-specifics markup detects RAM and SSD conflicts');
    await page.evaluate(()=>auditSettings({showItemPagePanel:false})); await wait(page);
    assert.equal(await panel.count(),0);
    ok('item panel switch removes the panel');

    await page.goto('https://www.ebay.com/mye/myebay'); await storage(page); await install(page); await wait(page);
    assert.equal(await page.locator('[data-ebay-helper-owned]').count(),0);
    ok('no waiting badge or scans on account pages');

    const popup=await context.newPage(); popup.on('pageerror',e=>errors.push(e.message));
    await popup.setViewportSize({width:392,height:600}); await popup.goto('https://audit.invalid/popup.html');
    await popup.setContent(fs.readFileSync(path.join(root,'popup.html'),'utf8').replace(/<script[\s\S]*?<\/script>/g,''));
    await storage(popup,{usdRate:44,markNewItems:false,showRiskBadges:false});
    await popup.addStyleTag({path:path.join(root,'popup.css')});
    await popup.addScriptTag({path:path.join(root,'core.js')}); await popup.addScriptTag({path:path.join(root,'popup.js')});
    assert.equal(await popup.locator('#usdRate').inputValue(),'44');
    assert.equal(await popup.locator('#markNewItems, #showRiskBadges').count(),0);
    assert.ok(await popup.locator('#saveButton').evaluate(el=>{const r=el.getBoundingClientRect();return r.top>=0 && r.bottom<=innerHeight;}));
    await popup.screenshot({path:path.join(artifacts,'popup.png'),fullPage:true});
    await popup.locator('#usdRate').fill('48'); await popup.locator('#saveButton').click();
    assert.equal(await popup.evaluate(()=>auditStored.ebayLaptopHelperSettings.usdRate),48);
    assert.equal(await popup.evaluate(()=>('markNewItems' in auditStored.ebayLaptopHelperSettings)),false);
    await popup.locator('#enabled').uncheck();
    await popup.locator('#resetButton').click();
    assert.equal(await popup.locator('#enabled').isChecked(),false);
    await popup.locator('#saveButton').click();
    assert.equal(await popup.evaluate(()=>auditStored.ebayLaptopHelperSettings.enabled),false);
    ok('popup save, legacy settings and reset preserve master switch');
    await popup.getByText('Перенесення налаштувань',{exact:true}).click();
    await popup.locator('#importFile').setInputFiles({name:'settings.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify({version:1,settings:{usdRate:51,showSoldSearch:false}}))});
    await popup.waitForFunction(()=>document.querySelector('#usdRate').value==='51');
    assert.equal(await popup.locator('#usdRate').inputValue(),'51');
    assert.equal(await popup.evaluate(()=>auditStored.ebayLaptopHelperSettings.usdRate),46);
    await popup.locator('#saveButton').click();
    assert.equal(await popup.evaluate(()=>auditStored.ebayLaptopHelperSettings.usdRate),51);
    await popup.locator('#importFile').setInputFiles({name:'invalid.json',mimeType:'application/json',buffer:Buffer.from('{}')});
    await popup.waitForFunction(()=>document.querySelector('#status').textContent.includes('Не вдалося'));
    assert.match(await popup.locator('#status').textContent(),/Не вдалося/);
    const download=popup.waitForEvent('download'); await popup.locator('#exportButton').click();
    assert.equal((await download).suggestedFilename(),'ebay-helper-settings.json');
    ok('settings import, validation and export');
    await popup.getByText('Кольори та слова у назві',{exact:true}).click();
    await popup.locator('#greenMaxUah').fill('20000'); await popup.locator('#yellowMaxUah').fill('10000');
    const writes=await popup.evaluate(()=>auditWrites);
    await popup.locator('#saveButton').click();
    assert.equal(await popup.evaluate(()=>auditWrites),writes);
    assert.match(await popup.locator('#yellowMaxUah').evaluate(el=>el.validationMessage),/Жовта межа/);
    await popup.locator('#yellowMaxUah').fill('30000');
    await popup.evaluate(()=>{chrome.storage.local.set=(values,callback)=>{chrome.runtime.lastError={message:'Test write failure'};callback();delete chrome.runtime.lastError;};});
    await popup.locator('#saveButton').click();
    assert.match(await popup.locator('#status').textContent(),/Test write failure/);
    assert.ok(await popup.locator('#saveButton').isEnabled());
    ok('invalid thresholds are rejected and failed saves keep editable values');
    const failedPopup=await context.newPage(); failedPopup.on('pageerror',e=>errors.push(e.message));
    await failedPopup.goto('https://audit.invalid/popup.html');
    await failedPopup.setContent(fs.readFileSync(path.join(root,'popup.html'),'utf8').replace(/<script[\s\S]*?<\/script>/g,''));
    await storage(failedPopup);
    await failedPopup.evaluate(()=>{chrome.storage.local.get=(keys,callback)=>{chrome.runtime.lastError={message:'Test read failure'};callback({});delete chrome.runtime.lastError;};});
    await failedPopup.addScriptTag({path:path.join(root,'core.js')}); await failedPopup.addScriptTag({path:path.join(root,'popup.js')});
    assert.equal(await failedPopup.locator('#saveButton').isEnabled(),false);
    assert.match(await failedPopup.locator('#status').textContent(),/Не вдалося прочитати/);
    ok('failed initial settings read cannot overwrite saved preferences');
    assert.deepEqual(errors,[]);
    console.log(`${passed} browser scenarios passed; screenshots: ${artifacts}`);
  } finally {await browser.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});
